// Code generated by templ@v0.2.364 DO NOT EDIT.

package public

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Login() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		err = DocType().Render(ctx, templBuffer)
		if err != nil {
			return err
		}
		err = Head().Render(ctx, templBuffer)
		if err != nil {
			return err
		}
		err = Body(pageLogin()).Render(ctx, templBuffer)
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}

func pageLogin() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_2 := templ.GetChildren(ctx)
		if var_2 == nil {
			var_2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<script async crossorigin=\"anonymous\" data-clerk-publishable-key=\"pk_test_cGVhY2VmdWwtb2FyZmlzaC0wLmNsZXJrLmFjY291bnRzLmRldiQ\" onload=\"window.Clerk.load()\" src=\"https://peaceful-oarfish-0.clerk.accounts.dev/npm/@clerk/clerk-js@4/dist/clerk.browser.js\" type=\"text/javascript\">")
		if err != nil {
			return err
		}
		var_3 := `
    `
		_, err = templBuffer.WriteString(var_3)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</script><button onclick=\"Clerk.openSignIn()\">")
		if err != nil {
			return err
		}
		var_4 := `Sign In`
		_, err = templBuffer.WriteString(var_4)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</button>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
