// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: companies_spill_users.sql

package db

import (
	"context"
)

const createCompanySpillUser = `-- name: CreateCompanySpillUser :exec
INSERT INTO companies_spill_users(spill_user_id, company_id) VALUES ($1, $2)
`

type CreateCompanySpillUserParams struct {
	SpillUserID int64
	CompanyID   int64
}

func (q *Queries) CreateCompanySpillUser(ctx context.Context, arg CreateCompanySpillUserParams) error {
	_, err := q.db.Exec(ctx, createCompanySpillUser, arg.SpillUserID, arg.CompanyID)
	return err
}
