// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CompaniesSpillUser struct {
	SpillUserID int64
	CompanyID   int64
}

type Company struct {
	ID           int64
	Name         string
	OverallScore pgtype.Numeric
}

type SpillUser struct {
	ID        int64
	Alias     string
	Bio       pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	ServiceID string
}
